---
layout: sidebar
style: dark
plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
permalink: /:year/:month/:day/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
projects:
  sort_by: stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects: null
social_media:
  instagram: calpicomai
  linkedin: callieborgerding
  twitter: calpicomai
  mastodon: @calpicomai
topics:
  - name: React
    web_url: https://github.com/meta/react
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png
  - name: GraphQL
    web_url: https://github.com/graphql
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/GraphQL_Logo.svg/2048px-GraphQL_Logo.svg.png
  - name: Bootstrap
    web_url: https://github.com/twbs/bootstrap
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Bootstrap_logo.svg/1280px-Bootstrap_logo.svg.png
